// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// FindNone provides a mock function for the type MockService
func (_mock *MockService) FindNone(ctx context.Context) string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindNone")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockService_FindNone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNone'
type MockService_FindNone_Call struct {
	*mock.Call
}

// FindNone is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) FindNone(ctx interface{}) *MockService_FindNone_Call {
	return &MockService_FindNone_Call{Call: _e.mock.On("FindNone", ctx)}
}

func (_c *MockService_FindNone_Call) Run(run func(ctx context.Context)) *MockService_FindNone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_FindNone_Call) Return(s string) *MockService_FindNone_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockService_FindNone_Call) RunAndReturn(run func(ctx context.Context) string) *MockService_FindNone_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNoneService creates a new instance of MockNoneService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNoneService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNoneService {
	mock := &MockNoneService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNoneService is an autogenerated mock type for the NoneService type
type MockNoneService struct {
	mock.Mock
}

type MockNoneService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNoneService) EXPECT() *MockNoneService_Expecter {
	return &MockNoneService_Expecter{mock: &_m.Mock}
}

// FindNone provides a mock function for the type MockNoneService
func (_mock *MockNoneService) FindNone(ctx context.Context) string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindNone")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockNoneService_FindNone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNone'
type MockNoneService_FindNone_Call struct {
	*mock.Call
}

// FindNone is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNoneService_Expecter) FindNone(ctx interface{}) *MockNoneService_FindNone_Call {
	return &MockNoneService_FindNone_Call{Call: _e.mock.On("FindNone", ctx)}
}

func (_c *MockNoneService_FindNone_Call) Run(run func(ctx context.Context)) *MockNoneService_FindNone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNoneService_FindNone_Call) Return(s string) *MockNoneService_FindNone_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockNoneService_FindNone_Call) RunAndReturn(run func(ctx context.Context) string) *MockNoneService_FindNone_Call {
	_c.Call.Return(run)
	return _c
}
