// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockNoneSvc creates a new instance of MockNoneSvc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNoneSvc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNoneSvc {
	mock := &MockNoneSvc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNoneSvc is an autogenerated mock type for the NoneSvc type
type MockNoneSvc struct {
	mock.Mock
}

type MockNoneSvc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNoneSvc) EXPECT() *MockNoneSvc_Expecter {
	return &MockNoneSvc_Expecter{mock: &_m.Mock}
}

// FindNone provides a mock function for the type MockNoneSvc
func (_mock *MockNoneSvc) FindNone(ctx context.Context) string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindNone")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockNoneSvc_FindNone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindNone'
type MockNoneSvc_FindNone_Call struct {
	*mock.Call
}

// FindNone is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNoneSvc_Expecter) FindNone(ctx interface{}) *MockNoneSvc_FindNone_Call {
	return &MockNoneSvc_FindNone_Call{Call: _e.mock.On("FindNone", ctx)}
}

func (_c *MockNoneSvc_FindNone_Call) Run(run func(ctx context.Context)) *MockNoneSvc_FindNone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNoneSvc_FindNone_Call) Return(s string) *MockNoneSvc_FindNone_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockNoneSvc_FindNone_Call) RunAndReturn(run func(ctx context.Context) string) *MockNoneSvc_FindNone_Call {
	_c.Call.Return(run)
	return _c
}
