// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMsgSvc creates a new instance of MockMsgSvc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMsgSvc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMsgSvc {
	mock := &MockMsgSvc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMsgSvc is an autogenerated mock type for the MsgSvc type
type MockMsgSvc struct {
	mock.Mock
}

type MockMsgSvc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMsgSvc) EXPECT() *MockMsgSvc_Expecter {
	return &MockMsgSvc_Expecter{mock: &_m.Mock}
}

// FindMsg provides a mock function for the type MockMsgSvc
func (_mock *MockMsgSvc) FindMsg(ctx context.Context, id string) string {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindMsg")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMsgSvc_FindMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMsg'
type MockMsgSvc_FindMsg_Call struct {
	*mock.Call
}

// FindMsg is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMsgSvc_Expecter) FindMsg(ctx interface{}, id interface{}) *MockMsgSvc_FindMsg_Call {
	return &MockMsgSvc_FindMsg_Call{Call: _e.mock.On("FindMsg", ctx, id)}
}

func (_c *MockMsgSvc_FindMsg_Call) Run(run func(ctx context.Context, id string)) *MockMsgSvc_FindMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMsgSvc_FindMsg_Call) Return(s string) *MockMsgSvc_FindMsg_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMsgSvc_FindMsg_Call) RunAndReturn(run func(ctx context.Context, id string) string) *MockMsgSvc_FindMsg_Call {
	_c.Call.Return(run)
	return _c
}
