pkgname: "mock"
packages:

  # DB MOCKS
  go-backend-skeleton/app/internal/svc/svcmsg:
    config:
      filename: mock_repo_msg.go
      dir: "app/internal/db/mock"
      all: true
  go-backend-skeleton/app/internal/svc/svcnone:
    config:
      filename: mock_repo_none.go
      dir: "app/internal/db/mock"
      all: true

  # SVC MOCKS
  go-backend-skeleton/app/internal/transport/http/httpmsg:
    config:
      filename: mock_svc_msg.go
      dir: "app/internal/svc/mock"
      all: true
  go-backend-skeleton/app/internal/transport/grpc/grpcmsg:
    config:
      filename: mock_svc_grpc_msg.go
      dir: "app/internal/svc/mock"
      all: true
  go-backend-skeleton/app/internal/transport/http/httpnone:
    config:
      filename: mock_svc_none.go
      dir: "app/internal/svc/mock"
      all: true

