pkgname: "mock"
filename: mock.go
packages:
  go-backend-skeleton/app/internal/db:
    config:
      dir: "{{.InterfaceDir}}/mock"
      all: true
  go-backend-skeleton/app/internal/svc:
    config:
      dir: "{{.InterfaceDir}}/mock"
      all: true

