pkgname: "mock"
packages:
  go-backend-skeleton/app/internal/svc/svcnone:
    config:
      filename: mock_repo_none.go
      dir: "app/internal/db/mock"
      all: true
  go-backend-skeleton/app/internal/transport/http/httpnone:
    config:
      filename: mock_svc_none.go
      dir: "app/internal/svc/mock"
      all: true

