// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMsgRepo creates a new instance of MockMsgRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMsgRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMsgRepo {
	mock := &MockMsgRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMsgRepo is an autogenerated mock type for the MsgRepo type
type MockMsgRepo struct {
	mock.Mock
}

type MockMsgRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMsgRepo) EXPECT() *MockMsgRepo_Expecter {
	return &MockMsgRepo_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockMsgRepo
func (_mock *MockMsgRepo) Find(ctx context.Context, id string) string {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMsgRepo_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockMsgRepo_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMsgRepo_Expecter) Find(ctx interface{}, id interface{}) *MockMsgRepo_Find_Call {
	return &MockMsgRepo_Find_Call{Call: _e.mock.On("Find", ctx, id)}
}

func (_c *MockMsgRepo_Find_Call) Run(run func(ctx context.Context, id string)) *MockMsgRepo_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMsgRepo_Find_Call) Return(s string) *MockMsgRepo_Find_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMsgRepo_Find_Call) RunAndReturn(run func(ctx context.Context, id string) string) *MockMsgRepo_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockMsgRepo
func (_mock *MockMsgRepo) Put(ctx context.Context, id string, msg string) error {
	ret := _mock.Called(ctx, id, msg)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, id, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMsgRepo_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockMsgRepo_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - msg string
func (_e *MockMsgRepo_Expecter) Put(ctx interface{}, id interface{}, msg interface{}) *MockMsgRepo_Put_Call {
	return &MockMsgRepo_Put_Call{Call: _e.mock.On("Put", ctx, id, msg)}
}

func (_c *MockMsgRepo_Put_Call) Run(run func(ctx context.Context, id string, msg string)) *MockMsgRepo_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMsgRepo_Put_Call) Return(err error) *MockMsgRepo_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMsgRepo_Put_Call) RunAndReturn(run func(ctx context.Context, id string, msg string) error) *MockMsgRepo_Put_Call {
	_c.Call.Return(run)
	return _c
}
