// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockNoneRepository creates a new instance of MockNoneRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNoneRepository(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockNoneRepository {
	mock := &MockNoneRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNoneRepository is an autogenerated mock type for the NoneRepository type
type MockNoneRepository struct {
	mock.Mock
}

type MockNoneRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNoneRepository) EXPECT() *MockNoneRepository_Expecter {
	return &MockNoneRepository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockNoneRepository
func (_mock *MockNoneRepository) Find(ctx context.Context) string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockNoneRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockNoneRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNoneRepository_Expecter) Find(ctx interface{}) *MockNoneRepository_Find_Call {
	return &MockNoneRepository_Find_Call{Call: _e.mock.On("Find", ctx)}
}

func (_c *MockNoneRepository_Find_Call) Run(run func(ctx context.Context)) *MockNoneRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNoneRepository_Find_Call) Return(s string) *MockNoneRepository_Find_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockNoneRepository_Find_Call) RunAndReturn(run func(ctx context.Context) string) *MockNoneRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}
